name: Sensor-Viewer-Doc

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: build 
          folder: dist
